# Generated by Django 6.0.3 on 2026-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=100, null=True, unique=True),
        ),
    ]
