# Generated by Django 6.0.3 on 2026-05-11 12:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
                ('objects', accounts.models.AccountsManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=100, unique=True),
        ),
    ]
