# Generated by Django 6.0.3 on 2026-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=models.FileField(blank=True, help_text='Upload video file (mp4, webm) - optional', null=True, upload_to='movie_trailers/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube embed link (optional)', null=True),
        ),
    ]
